# Generated by Django 4.0.6 on 2024-03-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='aplido',
            new_name='apelido',
        ),
    ]
