# Generated by Django 4.0.6 on 2024-05-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('ano_criacao', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('biografia', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_lancamento', models.IntegerField()),
                ('link', models.URLField()),
                ('duracao', models.IntegerField(null=True)),
                ('letra', models.TextField(blank=True, default='', null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('artista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='bandasrap.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_lancamento', models.IntegerField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='')),
                ('banda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='bandasrap.artista')),
                ('musicas', models.ManyToManyField(related_name='albuns', to='bandasrap.musica')),
            ],
        ),
    ]
