# Generated by Django 4.0.6 on 2024-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praia',
            old_name='região',
            new_name='regiao',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='servico',
        ),
        migrations.AddField(
            model_name='praia',
            name='servico',
            field=models.ManyToManyField(related_name='praias', to='praias.servico'),
        ),
    ]
