# Generated by Django 4.0.6 on 2024-04-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('objetivos', models.TextField()),
                ('competencias', models.TextField()),
                ('duracao', models.CharField(max_length=100)),
                ('vagas', models.IntegerField(default=0)),
                ('creditos', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('grau', models.IntegerField(blank=True, choices=[(1, 'Licenciatura'), (2, 'Mestrado'), (3, 'Mestrado Integrado'), (4, 'Douturamento'), (5, 'Pos-Graduação')], default=1, null=True)),
                ('localizacao', models.IntegerField(blank=True, choices=[(1, 'Centro Universitário Lisboa'), (2, 'Centro Universitário Porto')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=100)),
                ('ects', models.IntegerField()),
                ('curricularIUnitReadableCode', models.CharField(max_length=100)),
                ('areaCientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='curso.areacientifica')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('conceitos', models.TextField()),
                ('tecnologias', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='curso/fotos')),
                ('linkGit', models.URLField(default='/default-url/')),
                ('linkVideo', models.URLField(default='/default-url/')),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='curso.disciplina')),
                ('linguagemProgramacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='curso.linguagemprogramacao')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='docentes',
            field=models.ManyToManyField(related_name='disciplinas', to='curso.docente'),
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='curso.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='curso.disciplina')),
            ],
        ),
    ]
