# Generated by Django 4.0.6 on 2024-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.IntegerField(null=True),
        ),
    ]
