# Generated by Django 4.0.6 on 2024-03-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_album_banda_alter_musica_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='musicas',
            field=models.ManyToManyField(related_name='musicas', to='bandas.musica'),
        ),
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banda', to='bandas.banda'),
        ),
    ]
