# Generated by Django 4.0.6 on 2024-04-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_alter_musica_banda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='bandas.banda'),
        ),
        migrations.AlterField(
            model_name='album',
            name='musicas',
            field=models.ManyToManyField(related_name='albuns', to='bandas.musica'),
        ),
    ]
