# Generated by Django 4.0.6 on 2024-04-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_alter_album_banda_alter_album_musicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='musicas',
        ),
        migrations.AddField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='bandas.album'),
        ),
    ]
