# Generated by Django 4.0.6 on 2024-04-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0010_remove_album_musicas_musica_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='banda',
        ),
    ]
