# Generated by Django 4.0.6 on 2024-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0015_remove_musica_album_album_musicas_musica_banda'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(null=True),
        ),
    ]
