# Generated by Django 4.0.6 on 2024-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0017_remove_musica_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(null=True),
        ),
    ]
