# Generated by Django 4.0.6 on 2024-06-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uni', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Curso1',
        ),
    ]
