# Generated by Django 4.0.6 on 2024-06-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uni', '0002_rename_curso_curso1'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto1',
            name='cadeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadeira', to='Uni.cadeira1'),
        ),
    ]
