# Generated by Django 4.0.6 on 2024-03-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('fotoDePerfil', models.ImageField(upload_to='')),
                ('sobre', models.TextField(blank=True, default=1, null=True)),
                ('redeSocial', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
                ('comentario', models.TextField()),
                ('avaliacao', models.IntegerField(choices=[(1, 'Mau'), (2, 'Normal'), (4, 'Exelente'), (3, 'Bom')])),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('link', models.ImageField(blank=True, null=True, upload_to='')),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artigo', to='Artigos.autor')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Artigos.comentario')),
            ],
        ),
    ]
