# Generated by Django 4.0.6 on 2024-04-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0003_meuusuario_rename_redesocial_autor_rede_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Artigos.artigo'),
        ),
    ]
