# Generated by Django 4.0.6 on 2024-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artigos', '0004_remove_artigo_comentario_comentario_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='genero',
            field=models.CharField(blank=True, choices=[('Desporto', 'Desporto'), ('Economia', 'Economia'), ('Tecnologia', 'Tecnologia'), ('Noticias Mundo', 'Noticias Mundo')], max_length=50, null=True),
        ),
    ]
